# Generated by Django 3.1.2 on 2021-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210402_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
