# Generated by Django 3.1.2 on 2021-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210404_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon_class',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_name_plus_icon_class',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
