# Generated by Django 3.1.2 on 2021-04-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210404_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='menu_name_parent',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
