# Generated by Django 3.1.2 on 2021-04-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210404_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'python'), ('javascript', 'javascript'), ('django', 'django'), ('css', 'css'), ('html', 'html'), ('mysql', 'mysql'), ('postgresql', 'postgresql')], default='python', max_length=100, null=True),
        ),
    ]
