# Generated by Django 3.1.2 on 2021-04-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210417_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='theme_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
