# Generated by Django 3.1.2 on 2021-04-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_homepage_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='icon_class',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
