# Generated by Django 3.1.12 on 2021-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210624_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='inner_background_img',
            new_name='background_img',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='outer_background_img',
        ),
    ]
