# Generated by Django 3.1.12 on 2021-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210624_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default="TODAY'S CODE", max_length=200, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
