# Generated by Django 3.1.12 on 2021-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210624_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideos',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
