# Generated by Django 3.1.12 on 2021-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210625_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='language',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='style',
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube_video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
