# Generated by Django 3.1.12 on 2021-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210628_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dislikes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
